<#
.SYNOPSIS
    Regenerate docs/backlog.md from the idea sheet (Google Sheets CSV export) merged with the research data in
    docs/research/idea-research.json (feasibility, who needs it, hooks, existing mods). Ideas added to the sheet
    after the research show up as "not researched yet". Mods in src/ link themselves to an idea with <ModIdea>.
.PARAMETER Offline
    Use the ideas stored in idea-research.json instead of downloading the sheet.
.EXAMPLE
    ./tools/Update-Backlog.ps1
#>
[CmdletBinding()]
param([switch]$Offline)
$ErrorActionPreference = 'Stop'
Import-Module (Join-Path $PSScriptRoot 'lib\Common.psm1') -Force

$root = Get-RepoRoot
$sheetCsv = 'https://docs.google.com/spreadsheets/d/1nd_oWjYyphCcjt5F0SrstpkMK_UzDdKwj0U1UC3FHG0/export?format=csv'
$researchPath = Join-Path $root 'docs\research\idea-research.json'
$research = [IO.File]::ReadAllText($researchPath) | ConvertFrom-Json

# Me keep script ASCII (PS 5.1 read BOM-less script as ANSI). Fancy chars made at runtime.
$dot = [char]0x00B7; $arrow = [char]0x2192

function Norm([string]$x) { ($x -replace '[^A-Za-z0-9]', '').ToLower() }
function Cell([string]$x) { if ($null -eq $x) { return '' } ($x -replace '\|', '\|' -replace "`r?`n", ' ').Trim() }

# Me get sheet rows (category, name, description, scope, exists, link).
$rows = @()
if ($Offline) {
    $rows = $research.ideas | ForEach-Object { [pscustomobject]@{ c = $_.category; n = $_.name; d = $_.description; s = $_.scope; e = $_.existsPerUser; l = $_.userLink } }
} else {
    Write-Step 'Download idea sheet'
    $csv = (Invoke-WebRequest -Uri $sheetCsv -UseBasicParsing).Content
    $rows = $csv | ConvertFrom-Csv | Where-Object { $_.NAME } | ForEach-Object {
        [pscustomobject]@{ c = "$($_.CATEGORY)".Trim(); n = "$($_.NAME)".Trim(); d = "$($_.DESCRIPTION)".Trim(); s = "$($_.SCOPE)".Trim(); e = "$($_.'EXISTS ALREADY')".Trim(); l = "$($_.Link)".Trim() }
    }
    Write-Ok "$($rows.Count) ideas"
}

$byName = @{}
foreach ($i in $research.ideas) { $byName[(Norm $i.name)] = $i }

# Me find mods that implement an idea: <ModIdea> in csproj.
$modsByIdea = @{}
foreach ($p in Get-ModProjects) {
    $x = [xml](Get-Content $p.FullName -Raw)
    $pg = $x.Project.PropertyGroup | Select-Object -First 1
    $idea = $x.Project.PropertyGroup | ForEach-Object { $_.ModIdea } | Where-Object { $_ } | Select-Object -First 1
    if ($idea) {
        $rel = ($p.DirectoryName.Substring($root.Length + 1)) -replace '\\', '/'
        $modsByIdea[(Norm $idea)] = "[$($pg.ModName) $($pg.Version)](../$rel) (in development)"
    }
}

$sideText = @{ 'client-only' = 'Client'; 'host/server-only' = 'Server'; 'everyone' = 'Both'; 'depends' = 'Depends' }
$categories = 'Combat', 'Exploration', 'Farming', 'Cooking', 'Building', 'Crafting', 'UX'
$feasOrder = @{ trivial = 0; easy = 1; medium = 2; hard = 3; 'very-hard' = 4 }

$items = foreach ($r in $rows) {
    $res = $byName[(Norm $r.n)]
    [pscustomobject]@{
        Row = $r; Res = $res
        Feas = if ($res) { $res.feasibility } else { 'not researched yet' }
        Side = if ($res -and $sideText.ContainsKey($res.side)) { $sideText[$res.side] } elseif ($res) { $res.side } else { '?' }
        Assets = if ($res) { if ($res.needsAssets) { 'yes' } else { 'no' } } else { '?' }
        Coverage = if ($res -and $res.coverage) { $res.coverage } else { '?' }
        Status = if ($modsByIdea.ContainsKey((Norm $r.n))) { $modsByIdea[(Norm $r.n)] } else { 'idea' }
    }
}

$sb = New-Object System.Text.StringBuilder
function W([string]$line = '') { [void]$sb.AppendLine($line) }

W '# Idea backlog'
W ''
W "Generated by ``tools/Update-Backlog.ps1`` from [the idea sheet](https://docs.google.com/spreadsheets/d/1nd_oWjYyphCcjt5F0SrstpkMK_UzDdKwj0U1UC3FHG0/edit)"
W "and the research in ``docs/research/idea-research.json`` (game $($research.gameVersion), researched $($research.generated))."
W 'Do not edit by hand: change the sheet or the research data, then re-run the script.'
W ''
W "**Feasibility:** trivial $arrow easy $arrow medium $arrow hard $arrow very-hard. **Who needs it:** Client = only the player who wants it;"
W 'Server = the host/dedicated server; Both = server and every player; Depends = see details. **Assets:** needs custom'
W 'models, textures, animations or sounds. **Existing mods:** how much of it already exists on Nexus/Thunderstore'
W '(details and links per idea below; the game-systems chapters are in `docs/game/`).'
W ''

W '## Quick wins'
W ''
W 'QoL, trivial or easy, client-side only, no custom assets.'
W ''
W '| Idea | Category | Feasibility | Existing mods | Status |'
W '|---|---|---|---|---|'
$items | Where-Object { $_.Row.s -eq 'QoL' -and ($_.Feas -eq 'trivial' -or $_.Feas -eq 'easy') -and $_.Side -eq 'Client' -and $_.Assets -eq 'no' } |
    Sort-Object { $feasOrder[$_.Feas] }, { $_.Row.c } | ForEach-Object {
        W "| [$(Cell $_.Row.n)](#$((Cell $_.Row.n).ToLower() -replace '[^a-z0-9 -]', '' -replace ' ', '-')) | $($_.Row.c) | $($_.Feas) | $($_.Coverage) | $($_.Status) |"
    }
W ''

W '## Overview'
W ''
W '| Category | Idea | Scope | Feasibility | Who needs it | Assets | Existing mods | Status |'
W '|---|---|---|---|---|---|---|---|'
foreach ($c in $categories + @($items | ForEach-Object { $_.Row.c } | Where-Object { $categories -notcontains $_ } | Select-Object -Unique)) {
    $items | Where-Object { $_.Row.c -eq $c } | Sort-Object { @{ QoL = 0; Revamp = 1; New = 2 }[$_.Row.s] }, { $feasOrder[$_.Feas] } | ForEach-Object {
        W "| $c | $(Cell $_.Row.n) | $($_.Row.s) | $($_.Feas) | $($_.Side) | $($_.Assets) | $($_.Coverage) | $($_.Status) |"
    }
}
W ''

foreach ($c in $categories) {
    $group = $items | Where-Object { $_.Row.c -eq $c }
    if (-not $group) { continue }
    W "## $c"
    W ''
    foreach ($it in ($group | Sort-Object { @{ QoL = 0; Revamp = 1; New = 2 }[$_.Row.s] }, { $feasOrder[$_.Feas] })) {
        $r = $it.Row; $res = $it.Res
        W "### $(Cell $r.n)"
        W ''
        if ($r.d) { W "> $(Cell $r.d)"; W '' }
        W "- **Scope:** $($r.s) $dot **Feasibility:** $($it.Feas) $dot **Who needs it:** $($it.Side) $dot **Custom assets:** $($it.Assets) $dot **Status:** $($it.Status)"
        if ($res) {
            if ($res.sketch) { W "- **Approach:** $(Cell $res.sketch)" }
            if ($res.hooks) { W "- **Hooks:** $((@($res.hooks) | ForEach-Object { '`' + (Cell $_) + '`' }) -join ', ')" }
            if ($res.risks) { W "- **Risks:** $(Cell $res.risks)" }
            if ($res.relatedIdeas) { W "- **Related:** $((@($res.relatedIdeas) | ForEach-Object { Cell $_ }) -join '; ')" }
            if ($res.chapter) { W "- **Game systems:** [docs/game/$($res.chapter).md](game/$($res.chapter).md)" }
            W "- **Existing mods:** $($it.Coverage)$(if ($r.l) { " (sheet link: $($r.l))" })"
            $mods = @($res.existingMods)
            if ($mods.Count -gt 0 -and $mods[0]) {
                W ''
                W '  | Mod | Status | Notes |'
                W '  |---|---|---|'
                foreach ($m in $mods) { W "  | [$(Cell $m.name)]($($m.url)) | $(Cell $m.status) | $(Cell $m.notes) |" }
                W ''
            }
            if ($res.inspiration) { W "- **Inspiration:** $(Cell $res.inspiration)" }
        } else {
            W '- Not researched yet: run a research pass for this idea.'
        }
        W ''
    }
}

if ($research.infrastructure) {
    W '## Infrastructure proposed by the research'
    W ''
    W 'Shared building blocks the research agents recommended while assessing the ideas.'
    W ''
    foreach ($inf in $research.infrastructure) {
        W "### $(Cell $inf.name)"
        W ''
        W "- **Feasibility:** $($inf.feasibility) $dot **Who needs it:** $(if ($sideText.ContainsKey($inf.side)) { $sideText[$inf.side] } else { $inf.side })"
        if ($inf.sketch) { W "- **Approach:** $(Cell $inf.sketch)" }
        if ($inf.risks) { W "- **Risks:** $(Cell $inf.risks)" }
        W ''
    }
}

if ($research.notableMods) {
    W '## Notable mods to study'
    W ''
    W '| Mod | Why |'
    W '|---|---|'
    $research.notableMods | Sort-Object url -Unique | ForEach-Object { W "| [$(Cell $_.name)]($($_.url)) | $(Cell $_.why) |" }
    W ''
}

$out = Join-Path $root 'docs\backlog.md'
[IO.File]::WriteAllText($out, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Ok "docs/backlog.md ($($items.Count) ideas)"
